#
# Here will be all the default data based on enviroment
# On your local machine you can add new values
# Do not commit unnecessary values 
#

# TODO : need to add more enviroments and make difference for your local machines

default_config:
	DEFAULT_SDL_CLOUD_PRO_URL: 'https://languagecloud.sdl.com'
	DEFAULT_GRANT_TYPE: 'password'
	AUTH_TOKEN_URI = 'tm4lc/api/v1/auth/token';
	PROJECT_CREATION_OPTIONS_URI = 'tm4lc/api/v1/projects/options';
	FILE_UPLOAD_URI = 'tm4lc/api/v1/files/{projectOptionsId}';
	UPLOADED_FILE_URI = 'tm4lc/api/v1/files/{projectOptionsId}';
	CREATE_PROJECT_URI = '/tm4lc/api/v1/projects';
	APPROVE_PROJECT_URI = '/tm4lc/api/v1/projects/{projectId}';
	PROJECT_STATUS_URI = '/tm4lc/api/v1/projects/{projectId}';
	DOWNLOAD_FILE_URI = '/tm4lc/api/v1/files/{projectId}/{fileId}';
	PROJECT_QUOTE_URI = '/tm4lc/api/v1/projects/{projectId}/quote/{format}';
	PROJECTS_LIST_URI = 'tm4lc/api/v1/projects';
	CANCEL_PROJECT_URI = '/tm4lc/api/v1/projects/{projectId}';
	DOWNLOAD_TARGET_ZIP_URI = '/tm4lc/api/v1/projects/{projectId}/zip?types=TargetFiles';